Constants = {
    LINE_HEIGHT = 20,
    COLORS = {
        WHITE = { 247/255,  235/255,  233/255},
        YELLOW = { 209/255,  164/255,  29/255},
        GREEN = { 79/255,  247/255,  93/255},
    },
    FONTS = {
        NON_UNICODE = "Fonts\\FRIZQT__.TTF",
        UNICODE = "iFinder\\simhei.ttf", -- support for chinese simplified characters
    },
    INSTANCES = {
        	["Sunken Temple"] = {level = 45, aka = { " ST", "sunken temple", "sunken", "sunk", "sunkentemple", "神庙"}},
        	["Blackrock Depths"] = {level = 50, aka = {"blackrock depths", "blackrock dpths", "brd", "lava", "arena", "jailbreak", "黑石深渊"}},
    		["Dire Maul"] = {level = 60, aka = {"dm", "dire maul", "diremaul", "dmw", "dmn", "dme", "dm:w", "dm:n", "dm:e", "tribute", "trib", "厄运"}},
    		["Lower Blackrock Spire"] = {level = 60, aka = {"lower blackrock spire", "lower brs", "lower blackrock", "lbrs", "黑下", "黑石下"}},
    		["Upper Blackrock Spire"] = {level = 60, aka = {"upper blackrock spire", "upper brs", "upper blackrock", "ubrs", "黑上", "黑石上"}},
    		["Stratholme"] = {level = 60, aka = {"stratholme", "strath", "strat", "dk", "斯坦索姆"}},
            ["Scholomance"] = {level = 60, aka = {"scholomance", "scholo", "schol", "通灵学院"}},
    },
    TOKENS = {
    	["Lava Run"] = {"跳火", "lava", "lava run"},
    	["Emperor"] = {"皇帝", "emp", "emperor"},
    	["Full Run"] = {"全", "全通", "full", "full run"},
    	["Quest Run"] = {"任务", "quest", "quest run"},
    	["DM west"] = {"TODO"},
    	["DM east"] = {"TODO"},
    	["Dps"] = {"伤害", "damage", "dps"},
    	["Heals"] = {"治疗", "healer", "heals"},
    	["Tank"] = {"坦克", "tank", "来T", "要T", "和T", "T和"},
    	["melee dps"] = {"手伤", "melee"},
    	["Warrior"] = {"战士", "warrior"},
    	["Paladin"] = {"圣骑士", "paladin"},
    	["Hunter"] = {"猎人", "LR", "hunter"},
    	["Shaman"] = {"萨满", "shaman"},
    	["Rogue"] = {"盗贼", "rogue"},
    	["Druid"] = {"德鲁伊", "druid"},
    	["Mage"] = {"法师", "mage"},
    	["Warlock"] = {"术士", "warlock", "lock", "locke"},
    	["Priest"] = {"牧师", "priest"},
    	["Undead"] = {"dk", "undead"},
	},
	LFM_ARGS = {
		"lfm",
		"lf1m",
		"lf2m",
		"lf3m",
		"lf4m",
		"need",
		"spot",
		"lfdd",
		"lftank",
		"lfheal",
		"lfheals",
		"lfdps",
		"needed",
		"more for",
		"anyone for",
		"来",
		"开组",
	},
	LFG_ARGS = {
		"lfg",
		"求组",
	}
};